logging:
  level: INFO
  loggers:
    org.somik.todo: DEBUG

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

database:
  # the name of the JDBC driver
  driverClass: com.mysql.jdbc.Driver
  # database username
  user: todo
  # database password
  password: 68yqU1eqg0JfvFTO
  # the JDBC URL for database (db is the docker container name)
  url: jdbc:mysql://db:3306/todo
  # any properties specific to the JDBC driver:
  properties:
    charSet: UTF-8
  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 15s
  autoReconnect: true
  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"
  # the timeout before a connection validation queries fail
  validationQueryTimeout: 10s
  # the minimum number of connections to keep open
  minSize: 8
  # the maximum number of connections to keep open
  maxSize: 32
  # whether or not idle connections should be validated
  checkConnectionWhileIdle: true
  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s
  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute